KusionStack/konfig

- base/examples/kcl-vault-agent/base/base.k
- base/examples/kcl-vault-csi/dev/main.k
- base/pkg/kusion_models/kube/frontend/server.k
Server Model must have labels and selector, so I changed default to True.
> bugfix: default build-in labels and selectors as True

- .github/workflows/main.yml
- appops/guestbook-frontend/pre/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/prod/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/test/ci-test/stdout.golden.yaml
- appops/http-echo/dev/ci-test/stdout.golden.yaml
- appops/nginx-example/dev/ci-test/stdout.golden.yaml
- base/examples/job-example/dev/ci-test/stdout.golden.yaml
- base/examples/kcl-vault-agent/dev/ci-test/stdout.golden.yaml
- base/examples/kcl-vault-csi/dev/ci-test/stdout.golden.yaml
- base/examples/monitoring/prometheus-example-app/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_config_map/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_label_selector/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_main_container/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_need_namespace/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_scheduling_strategy/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_secret/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_service/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_sidecar/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_stateful_set/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_volume/prod/ci-test/stdout.golden.yaml
- hack/compile-rocket.py
- hack/test_konfig.py
- hack/verify-project-structure.py
> bugfix: correct kusion image address

- .github/workflows/main.yml
close: https://github.com/KusionStack/konfig/issues/14
> fix: change kusion-action to officail one

- base/examples/server/app_main_container/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_main_container/prod/main.k
- base/pkg/kusion_models/kube/utils/container_frontend2kube.k
fix: #18
```release-note
None
```
> fix: container frontend 2 kube function.

- base/pkg/kusion_models/kube/utils/str2resource_requirements.k
fix https://github.com/KusionStack/konfig/issues/20
> fix: index check for SchedulingStrategy.resource of type string

- base/pkg/kusion_models/kube/backend/server_backend.k
- [✅] N
kusionstack
- [✅] Other
- [✅] N
- [✅] Other
```release-note
None
```
> Feat add hostpath in OLUME_SOURCE_TYPE_MAPPING

- appops/guestbook-frontend/pre/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/prod/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/test/ci-test/stdout.golden.yaml
- appops/http-echo/dev/ci-test/stdout.golden.yaml
- appops/nginx-example/dev/ci-test/stdout.golden.yaml
- base/examples/job-example/dev/ci-test/stdout.golden.yaml
- base/examples/kcl-vault-agent/dev/ci-test/stdout.golden.yaml
- base/examples/kcl-vault-csi/dev/ci-test/stdout.golden.yaml
- base/examples/monitoring/prometheus-example-app/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_config_map/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_label_selector/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_main_container/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_need_namespace/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_scheduling_strategy/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_secret/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_service/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_sidecar/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_stateful_set/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_volume/prod/ci-test/stdout.golden.yaml
- base/pkg/kusion_models/kube/mixins/output_type_mixin.k
appops/
base/
update kusion spec model, add type field
```release-note
None
```
> update kusion spec model

- .github/workflows/lint.yml
- base/examples/kcl-vault-agent/base/base.k
- base/examples/kcl-vault-agent/dev/main.k
- base/examples/kcl-vault-csi/base/base.k
- base/examples/kcl-vault-csi/dev/main.k
- base/examples/monitoring/prometheus-example-app/base/base.k
- base/examples/monitoring/prometheus-example-app/prod/main.k
- base/examples/server/app_config_map/base/base.k
- base/examples/server/app_label_selector/base/base.k
- base/examples/server/app_main_container/base/base.k
- base/examples/server/app_need_namespace/base/base.k
- base/examples/server/app_need_namespace/prod/main.k
- base/examples/server/app_scheduling_strategy/base/base.k
- base/examples/server/app_secret/base/base.k
- base/examples/server/app_service/base/base.k
- base/examples/server/app_sidecar/prod/main.k
- base/examples/server/app_stateful_set/base/base.k
- base/pkg/kusion_models/kube/frontend/server.k
- base/pkg/kusion_models/kube/frontend/serviceaccount/service_account.k
- base/pkg/kusion_models/kube/utils/application_builder.k
- hack/lint_check.py
.github/workflows 
Add lint check to github action, fix exist lint warnings.
CI test
failed case
success case
```release-note
None
```
> Feat: add lint check to action

- base/pkg/kusion_models/kube/frontend/ingress/ingress.k
- base/pkg/kusion_models/kube/mixins/ingress_mixin.k
base/
```release-note
None
```
> support tls settings for kusion_models/fontend/ingress

- base/pkg/kusion_models/kube/frontend/container/env/env.k
- base/pkg/kusion_models/kube/utils/container_frontend2kube.k
> feat: add ResourceFieldSelector, support env.valueFrom.resourceFieldRef

- .github/workflows/main.yml
- hack/lib/utils.py
- hack/test_konfig.py
- hack/verify-project-structure.py
fix #24 
.github/workflow/main.yml
hack/test_config.py
hack/ver
hack/lib/utils.py
this PR supports dependency analysis in konfig ci pipeline. Only projects/stacks affected by the changed files will be tested and checked to save time.
Here's an example of a ci pipeline that's triggered by the change of ```base/pkg/kusion_models/kube/frontend/server.k```: https://github.com/KusionStack/konfig/actions/runs/2859662619
and here's an example about file changing barely under specific stack: https://github.com/KusionStack/konfig/actions/runs/2859947818
the example cases of this PR have been shown above.
```release-note
None
```
> support dependency analysis in CI

- hack/lint_check.py
the lint check script is broken after merging PR #16 , this PR fixes it to the full.
- hack/lint_check.py
here's an example of the effect of lint check after this fix, and it works fine now: https://github.com/KusionStack/konfig/actions/runs/3278253763/jobs/5396444153
```release-note
None
```
> fix lint check script

- base/examples/monitoring/prometheus-install/base/base.k
- base/examples/monitoring/prometheus-install/prod/ci-test/settings.yaml
- base/examples/monitoring/prometheus-install/prod/ci-test/stdout.golden.yaml
- base/examples/monitoring/prometheus-install/prod/kcl.yaml
- base/examples/monitoring/prometheus-install/prod/main.k
- base/examples/monitoring/prometheus-install/prod/stack.yaml
- base/examples/monitoring/prometheus-install/project.yaml
- base/pkg/kusion_models/kube/render/render.k
```release-note
one-click deploy alertmanager integrating with prometheus
```
> feat: one-click deploy alertmanager integrating with prometheus

- base/examples/monitoring/prometheus-rules/alert/ci-test/settings.yaml
- base/examples/monitoring/prometheus-rules/alert/ci-test/stdout.golden.yaml
- base/examples/monitoring/prometheus-rules/alert/kcl.yaml
- base/examples/monitoring/prometheus-rules/alert/main.k
- base/examples/monitoring/prometheus-rules/alert/stack.yaml
- base/examples/monitoring/prometheus-rules/project.yaml
- base/examples/monitoring/prometheus-rules/record/ci-test/settings.yaml
- base/examples/monitoring/prometheus-rules/record/ci-test/stdout.golden.yaml
- base/examples/monitoring/prometheus-rules/record/kcl.yaml
- base/examples/monitoring/prometheus-rules/record/main.k
- base/examples/monitoring/prometheus-rules/record/stack.yaml
related issue: https://github.com/KusionStack/konfig/issues/45#issuecomment-1288922110
> feat: new sample for prometheus rules

- base/examples/monitoring/prometheus-install/prod/ci-test/stdout.golden.yaml
- base/examples/monitoring/prometheus-install/prod/main.k
- base/examples/monitoring/prometheus-rules/alert/ci-test/stdout.golden.yaml
- base/examples/monitoring/prometheus-rules/alert/main.k
- base/examples/monitoring/prometheus-rules/record/ci-test/stdout.golden.yaml
- base/examples/monitoring/prometheus-rules/record/main.k
related issue: https://github.com/KusionStack/kusionstack.io/issues/176
> chore: rename resources to be practical

- .devcontainer.json
re https://github.com/KusionStack/kusion/issues/163
.devcontainer.json
```release-note
support the devcontainer configuration to open in GitHub codespaces.
```
> add .devcontainer.json

- appops/guestbook-frontend/base/base.k
- appops/guestbook-frontend/pre/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/prod/ci-test/settings.yaml
- appops/guestbook-frontend/prod/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/test/ci-test/stdout.golden.yaml
> publish service config for gb-frontend

- appops/http-echo/dev/ci-test/stdout.golden.yaml
- appops/nginx-example/dev/ci-test/stdout.golden.yaml
- base/examples/job-example/dev/ci-test/stdout.golden.yaml
- base/examples/kcl-vault-agent/dev/ci-test/stdout.golden.yaml
- base/examples/kcl-vault-csi/dev/ci-test/stdout.golden.yaml
- base/examples/server/app_config_map/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_label_selector/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_main_container/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_need_namespace/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_scheduling_strategy/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_secret/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_service/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_sidecar/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_stateful_set/prod/ci-test/stdout.golden.yaml
- base/examples/server/app_volume/prod/ci-test/stdout.golden.yaml
> fix key-value order in golden yaml files

- appops/guestbook-frontend/base/base.k
- appops/guestbook-frontend/pre/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/pre/main.k
- appops/guestbook-frontend/prod/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/prod/main.k
- appops/guestbook-frontend/test/ci-test/stdout.golden.yaml
- appops/guestbook-frontend/test/main.k
- appops/http-echo/base/base.k
- appops/http-echo/dev/ci-test/stdout.golden.yaml
> fix examples to be deployed successfully

- .devcontainer.json
.devcontainer.json
update .devcontainer.json with kusion quick start env, so that the vscode-kusion can recognize it and provider user friendly hint for minikube interaction in quick start 
```release-note
None
```
> update .devcontainer.json with kusion quick start env

- base/pkg/kusion_clouds/alicloud/alicloud_instance.k
- base/pkg/kusion_clouds/alicloud/alicloud_oss_bucket.k
- base/pkg/kusion_clouds/alicloud/alicloud_security_group.k
- base/pkg/kusion_clouds/alicloud/alicloud_slb.k
- base/pkg/kusion_clouds/alicloud/alicloud_vpc.k
- base/pkg/kusion_clouds/alicloud/alicloud_vswitch.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_config.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_instance_backend.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_oss_backend.k
- base/pkg/kusion_models/commons/resource.k
- base/pkg/kusion_models/commons/resource_builder.k
- clouds/alicloud/alicloud_instance/instance/ci-test/settings.yaml
- clouds/alicloud/alicloud_instance/instance/ci-test/stdout.golden.yaml
- clouds/alicloud/alicloud_instance/instance/kcl.yaml
- clouds/alicloud/alicloud_instance/instance/main.k
- clouds/alicloud/alicloud_instance/instance/stack.yaml
- clouds/alicloud/alicloud_instance/project.yaml
base/pkg/kusion_clouds/alicloud
clouds/alicloud/alicloud_instance
```release-note
None
```
> add alicloud instance example

- base/pkg/kusion_clouds/alicloud/alicloud_instance.k
- base/pkg/kusion_clouds/alicloud/alicloud_oss_bucket.k
- base/pkg/kusion_clouds/alicloud/alicloud_security_group.k
- base/pkg/kusion_clouds/alicloud/alicloud_slb.k
- base/pkg/kusion_clouds/alicloud/alicloud_vpc.k
- base/pkg/kusion_clouds/alicloud/alicloud_vswitch.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_config.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_instance_backend.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_oss_backend.k
- base/pkg/kusion_models/commons/resource.k
- base/pkg/kusion_models/commons/resource_builder.k
- clouds/alicloud/alicloud_instance/instance/ci-test/settings.yaml
- clouds/alicloud/alicloud_instance/instance/ci-test/stdout.golden.yaml
- clouds/alicloud/alicloud_instance/instance/kcl.yaml
- clouds/alicloud/alicloud_instance/instance/main.k
- clouds/alicloud/alicloud_instance/instance/stack.yaml
- clouds/alicloud/alicloud_instance/project.yaml
- clouds/alicloud/alicloud_oss/oss/ci-test/settings.yaml
- clouds/alicloud/alicloud_oss/oss/ci-test/stdout.golden.yaml
- clouds/alicloud/alicloud_oss/oss/kcl.yaml
- clouds/alicloud/alicloud_oss/oss/main.k
- clouds/alicloud/alicloud_oss/oss/stack.yaml
- clouds/alicloud/alicloud_oss/project.yaml
> Add alicloud oss bucket

- .github/workflows/lint.yml
- .github/workflows/main.yml
> fix workflow script: install necessary pytest modules before testing

- base/pkg/kusion_models/kube/backend/server_backend.k
In the upcoming official version of KCL v0.4.4, we will strengthen the static type check of KCL (follow the type invariability), so we will adjust Konfig's current code slightly to maintain compatibility.
`_workloadInstance` needs to display the joint type marked as `Deployment` and `StatefulSet`, otherwise the KCL compiler will derive the type conflict information of `Deployment` and `StatefulSet`
All konfig appops integration tests.
```release-note
None
```
> refactor: add workload instance type annotation.

- base/examples/secret-as-code/base/base.k
- base/examples/secret-as-code/dev/ci-test/settings.yaml
- base/examples/secret-as-code/dev/ci-test/stdout.golden.yaml
- base/examples/secret-as-code/dev/kcl.yaml
- base/examples/secret-as-code/dev/main.k
- base/examples/secret-as-code/dev/stack.yaml
- base/examples/secret-as-code/project.yaml
related: https://github.com/KusionStack/kusion/issues/149#issuecomment-1311200340
> example: secret as code

- appops/wordpress/README.md
- appops/wordpress/base/base.k
- appops/wordpress/dev/ci-test/settings.yaml
- appops/wordpress/dev/ci-test/stdout.golden.yaml
- appops/wordpress/dev/kcl.yaml
- appops/wordpress/dev/main.k
- appops/wordpress/dev/stack.yaml
- appops/wordpress/project.yaml
- base/pkg/kusion_clouds/alicloud_backend/alicloud_oss_backend.k
- base/pkg/kusion_models/kube/backend/server_backend.k
- base/pkg/kusion_models/kube/frontend/server.k
- base/pkg/kusion_models/kube/frontend/storage/objectstorage.k
- base/pkg/kusion_models/kube/render/render.k
appops/wordpress/
```release-note
None
```
> add wordpress example

- base/pkg/kusion_clouds/alicloud_backend/alicloud_config.k
base/pkg/kusion_clouds/alicloud_backend/alicloud_config.k
support pass the alicloud ak sk from option
```release-note
None
```
> set alicloud ak sk from option

- appops/http-echo/base/base.k
- appops/http-echo/dev/ci-test/stdout.golden.yaml
fix #92 
appops/http-echo/base/base.k
```release-note
None
```
> fix: backend service name in http-echo

- .github/workflows/main.yml
- hack/test_konfig.py
fix: https://github.com/KusionStack/konfig/issues/95
```release-note
None
```
> chore: update test scripts to be compatible with new kusion compile output

- base/pkg/kusion_clouds/alicloud/alicloud_cs_managed_kubernetes.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_managed_kubernetes_backend.k
- clouds/alicloud/alicloud_kubernetes/ack/ci-test/settings.yaml
- clouds/alicloud/alicloud_kubernetes/ack/ci-test/stdout.golden.yaml
- clouds/alicloud/alicloud_kubernetes/ack/kcl.yaml
- clouds/alicloud/alicloud_kubernetes/ack/main.k
- clouds/alicloud/alicloud_kubernetes/ack/stack.yaml
- clouds/alicloud/alicloud_kubernetes/project.yaml
base/pkg/kusion_clouds/alicloud_backend/
base/pkg/kusion_clouds/alicloud/
clouds/alicloud/alicloud_kubernetes/
```release-note
None
```
> add alicloud ack example

- appops/wordpress/base/base.k
- appops/wordpress/dev/main.k
refactor: bump top level `=` to `:` because the feature will be deprecated in kclvm v0.4.6
```release-note
None
```
> refactor: bump top level `=` to `:` because the feature will be deprecated in kclvm v0.4.6

- appops/wordpress-kubevela/README.md
- appops/wordpress-kubevela/base/base.k
- appops/wordpress-kubevela/dev/ci-test/settings.yaml
- appops/wordpress-kubevela/dev/ci-test/stdout.golden.yaml
- appops/wordpress-kubevela/dev/kcl.yaml
- appops/wordpress-kubevela/dev/main.k
- appops/wordpress-kubevela/dev/platform.k
- appops/wordpress-kubevela/dev/stack.yaml
- appops/wordpress-kubevela/project.yaml
- appops/wordpress/dev/ci-test/stdout.golden.yaml
- base/pkg/kusion_clouds/alicloud/alicloud_db_connection.k
- base/pkg/kusion_clouds/alicloud/alicloud_db_instance.k
- base/pkg/kusion_clouds/alicloud/alicloud_rds_account.k
- base/pkg/kusion_clouds/alicloud/alicloud_vpc.k
- base/pkg/kusion_clouds/alicloud/alicloud_vswitch.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_config.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_instance_backend.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_oss_backend.k
- base/pkg/kusion_clouds/alicloud_backend/alicloud_rds_backend.k
- base/pkg/kusion_models/commons/resource_builder.k
- base/pkg/kusion_models/kube/backend/server_backend.k
- base/pkg/kusion_models/kube/frontend/server.k
- base/pkg/kusion_models/kube/frontend/storage/database.k
- base/pkg/kusion_models/kube/render/render.k
- clouds/alicloud/alicloud_instance/instance/ci-test/stdout.golden.yaml
- clouds/alicloud/alicloud_instance/instance/main.k
- clouds/alicloud/alicloud_oss/oss/ci-test/stdout.golden.yaml
Ref: #87 
modified: 
base/pkg/kusion_models/kube/frontend/server.k
base/pkg/kusion_models/kube/render/render.k
base/pkg/kusion_models/kube/backend/server_backend.k
added: 
base/pkg/kusion_clouds/alicloud/alicloud_db_connection.k
base/pkg/kusion_clouds/alicloud/alicloud_db_instance.k
base/pkg/kusion_clouds/alicloud/alicloud_rds_account.k
base/pkg/kusion_clouds/alicloud_backend/alicloud_rds_backend.k
base/pkg/kusion_models/kube/frontend/storage/database.k
appops/wordpress-kubevela
A new item "renderType" is added in server frontend to support rendering KubeVela Application, and a related wordpress example is given, along with relevant alicloud rds resource schemas for hybrid resource support. 
Please refer to [Release Notes Language Style …
> add supports for wordpress example demo with KubeVela Application and related Alicloud RDS resources

- appops/wordpress/README.md
- appops/wordpress/base/base.k
- appops/wordpress/dev/ci-test/settings.yaml
- appops/wordpress/dev/ci-test/stdout.golden.yaml
- appops/wordpress/dev/kcl.yaml
- appops/wordpress/dev/main.k
- appops/wordpress/dev/platform.k
This PR modifies the files in konfig/appops/wordpress
This PR revises the original wordpress example with hybrid resources from Kubernetes + Alicloud OSS to Kubernetes + Alicloud RDS, using the Alicloud RDS as the database backend. 
This PR changes the original wordpress example. Alicloud OSS seems not fitting well with the original demo, thus we decided to use Alicloud RDS for better demonstration. 
As shown in konfig/appops/wordpress/README.md, executing `kusion apply --yes` can successfully apply the Alicloud and Kubernetes resources. 
```release-note
None
```
> revise the original wordpress example with Alicloud RDS as database backend

- appops/wordpress-kubevela/README.md
- appops/wordpress-kubevela/dev/main.k
- appops/wordpress/README.md
- appops/wordpress/dev/main.k
… comments for code instructions
This PR affected appops/wordpress and appops/wordpress-kubevela. 
This PR fixed a typo in README.md of wordpress examples and added some comments for code instructions. 
```release-note
None
```
> chore: fixed a typo and added some comments for wordpress examples

- appops/wordpress-kubevela/dev/ci-test/stdout.golden.yaml
- appops/wordpress/dev/ci-test/stdout.golden.yaml
This PR changed appops/wordpress and appops/wordpress-kubevela. 
This PR recompile wordpress and wordpress-kubevela to fix ci failures
```release-note
None
```
> fix: recompile wordpress and wordpress-kubevela to fix ci failures

- .github/workflows/lint.yml
- .github/workflows/main.yml
fix #108 
/workflow
Affects user behaviors
No
None
```release-note
None
```
> upgrade github actions, delete job "apply"

- appops/wordpress/dev/ci-test/stdout.golden.yaml
- appops/wordpress/dev/main.k
add env in the WordPress for test
> add env in the WordPress

- .github/workflows/main.yml
- base/pkg/kusion_models/kube/render/render.k
refactor: bump {str:[]} to ResourceMapping type for correct runtime ty check
Before KCL v0.5.0, KCL was unable to detect a type mismatch between `{str: []}` and `resource.ResourceMapping`. Therefore, this compatible PR correction code was proposed to match the latest version of KCL.
+ base/pkg/kusion_models/kube/render/render.k
```release-note
None
```
> refactor: bump {str:[]} to ResourceMapping type for correct runtime ty check

- base/pkg/kusion_models/kube/frontend/strategy/scheduling_strategy.k
- base/pkg/kusion_models/kube/utils/str2resource_requirements.k
fix https://github.com/KusionStack/konfig/issues/118
utils/str2resource_requirements.k
```release-note
None
```
> add patch-add-resourceRequirements for SchedulingStrategy

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/enhancement.yaml
- .github/ISSUE_TEMPLATE/failing-test.yaml
- .github/PULL_REQUEST_TEMPLATE.md
> add issue and PR templates

- base/pkg/kusion_models/kube/frontend/container/container.k
#122
konfig/base/pkg/kusion_models/kube/frontend/container/container.k
```release-note
None
```
> add-container-image-pull-policy

- example/multi-stack/base/base.k
/kind test
test: update config of multi-stack, export service at port 8080
> test: update config of multi-stack, export service at port 8080

- example/nginx/dev/main.k
/kind feat
fix: niginx container name
> fix: niginx container name

- example/nginx/dev/kcl.mod
- example/nginx/dev/main.k
- example/nginx/dev/stack.yaml
- example/nginx/dev/workspace.yaml
- example/nginx/project.yaml
- example/sample-job/prod/kcl.mod
/kind feature
Add sample nginx
> feat: add sample nginx

- example/service-multi-stack/dev/kcl.mod
- example/service-multi-stack/prod/kcl.mod
Fixes #
```release-note
```
```docs
```
> feat: update example service-multi-stack

- example/nginx/dev/kcl.mod
- example/sample-job/prod/kcl.mod
- example/service-multi-stack/dev/kcl.mod
- example/service-multi-stack/prod/kcl.mod
- example/simple-service/prod/kcl.mod
- example/wordpress/dev/kcl.mod
Fixes #
```release-note
```
```docs
```
> feat: update edition and catalog tag

- example/nginx/dev/kcl.mod
- example/nginx/dev/main.k
- example/service-multi-stack/base/base.k
- example/service-multi-stack/dev/kcl.mod
- example/service-multi-stack/dev/main.k
- example/service-multi-stack/prod/kcl.mod
- example/service-multi-stack/prod/main.k
- example/simple-job/dev/kcl.mod
- example/simple-job/dev/main.k
- example/simple-service/dev/kcl.mod
- example/simple-service/dev/main.k
- example/wordpress-cloud-rds/prod/kcl.mod
- example/wordpress-cloud-rds/prod/main.k
- example/wordpress-local-db/prod/kcl.mod
- example/wordpress-local-db/prod/main.k
Fixes #
```release-note
```
```docs
```
> docs: update examples to reflect kusion modules

- example/quickstart/default/kcl.mod
- example/quickstart/default/main.k
- example/quickstart/default/stack.yaml
- example/quickstart/project.yaml
/kind feature
This PR adds a demo application named `quickstart` to demonstrate the `preview` and `apply` GitHub Actions workflow. 
Fixes #
```release-note
```
```docs
```
> feat: add quickstart demo application

- .github/workflows/apply.yml
- .github/workflows/preview.yml
- .gitignore
- example/nginx/dev/kcl.mod
- example/nginx/dev/main.k
- example/nginx/project.yaml
- example/service-multi-stack/base/base.k
- example/service-multi-stack/dev/kcl.mod
- example/service-multi-stack/dev/main.k
- example/service-multi-stack/prod/kcl.mod
- example/service-multi-stack/prod/main.k
- example/service-multi-stack/project.yaml
- example/simple-job/dev/kcl.mod
- example/simple-job/dev/main.k
- example/simple-job/project.yaml
- example/simple-service/dev/kcl.mod
- example/simple-service/dev/main.k
- example/wordpress-cloud-rds/prod/kcl.mod
- example/wordpress-cloud-rds/prod/main.k
- example/wordpress-cloud-rds/project.yaml
- example/wordpress-local-db/prod/kcl.mod
- example/wordpress-local-db/prod/main.k
/kind feature
This PR updates the example apps of konfig repository. 
Fixes #
```release-note
```
```docs
```
> feat: update example apps

- .github/workflows/apply.yml
- .github/workflows/preview.yml
/kind feature
This PR updates the application deployment workflow config file `.github/workflows/apply.yml`. 
Fixes https://github.com/KusionStack/kusion/issues/1229
```release-note
```
```docs
```
> feat: update application deployment workflow
